[pytest]
filterwarnings =
    error
    ignore::DeprecationWarning:keras.*
    ignore::DeprecationWarning:firebase_admin.*
    ignore::UserWarning:sklearn.*
    ignore::DeprecationWarning:google.protobuf.*
