[pytest]
norecursedirs = data
python_files = test_assistant.py test_fault.py test_notification.py test_pdf_report.py test_renewable.py test_system_health.py test_theft.py test_transformer.py test_validation.py api_auth_test.py

filterwarnings =
    error
    ignore:.*'crypt' is deprecated.*:DeprecationWarning
    ignore::DeprecationWarning:keras.*
    ignore::DeprecationWarning:firebase_admin.*
    ignore::UserWarning:sklearn.*
    ignore::DeprecationWarning:google.protobuf.*
    ignore:.*Setting the shape on a NumPy array has been deprecated.*:DeprecationWarning
    ignore::DeprecationWarning:joblib.*

